import { Database, SidebarNavItem } from "@/types";

export const databaseClusters: DatabaseCluster[] = [
	{
		id: "1",
		name: "Database 1",
		host: "Host 1",
		port: "port1",
		type: "postgres",
		username: "admin1",
		password: "password1",
	},
	{
		id: "2",
		name: "Database 2",
		host: "Host 2",
		port: "port2",
		type: "sqllite",
		username: "admin2",
		password: "password2",
	},
	{
		id: "3",
		name: "Database 3",
		host: "Host 3",
		port: "port3",
		type: "postgres",
		username: "admin3",
		password: "password3",
	},
	{
		id: "4",
		name: "Database 4",
		host: "Host 4",
		port: "port4",
		type: "postgres",
		username: "admin4",
		password: "password4",
	},
	{
		id: "5",
		name: "Database 5",
		host: "Host 5",
		port: "port5",
		type: "mssql",
		username: "admin5",
		password: "password5",
	},
	{
		id: "6",
		name: "Database 6",
		host: "Host 6",
		port: "port6",
		type: "mysql",
		username: "admin6",
		password: "password6",
	},
];

export const databases: any = {
	"1": [
		{ name: "database-1a" },
		{ name: "database-1b" },
		{ name: "database-1c" },
		{ name: "database-1d" },
		{ name: "database-1e" },
		{ name: "database-1f" },
	],
	"2": [
		{ name: "database-2a" },
		{ name: "database-2b" },
		{ name: "database-2c" },
		{ name: "database-2d" },
		{ name: "database-2e" },
		{ name: "database-2f" },
	],
	"3": [
		{ name: "database-3a" },
		{ name: "database-3b" },
		{ name: "database-3c" },
		{ name: "database-3d" },
		{ name: "database-3e" },
		{ name: "database-3f" },
	],
	"4": [
		{ name: "database-4a" },
		{ name: "database-4b" },
		{ name: "database-4c" },
		{ name: "database-4d" },
		{ name: "database-4e" },
		{ name: "database-4f" },
	],
};

export const tables: any = {
	"database-1a": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-1b": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-1c": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-1d": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-1e": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-1f": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-2a": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-2b": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-2c": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-2d": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-2e": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-2f": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-3a": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-3b": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-3c": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-3d": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-3e": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-3f": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-4a": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-4b": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-4c": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-4d": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-4e": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
	"database-4f": [
		{ name: "table-1a" },
		{ name: "table-1b" },
		{ name: "table-1c" },
		{ name: "table-1d" },
		{ name: "table-1e" },
		{ name: "table-1f" },
	],
};
